# Generated by Django 3.2.13 on 2022-10-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('esta_permiso', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('kg', models.FloatField(blank=True, null=True)),
                ('lt', models.FloatField(blank=True, null=True)),
                ('stock', models.BigIntegerField()),
                ('ultima_repo', models.DateField()),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id_carta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_carta', models.CharField(max_length=100)),
                ('precio', models.BigIntegerField()),
            ],
            options={
                'db_table': 'carta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('anotaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id_ingrediente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ingredientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id_merma', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'merma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_personas', models.BigIntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_orden', models.CharField(max_length=100)),
                ('kg', models.FloatField(blank=True, null=True)),
                ('lt', models.FloatField(blank=True, null=True)),
                ('cantidad', models.BigIntegerField()),
                ('fecha_orden', models.DateField()),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.BigIntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_receta', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_re', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('telefono', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
